@startuml

actor CEO as "CEO"

rectangle Database

rectangle "Global Reporting System" {

    usecase Choice as "Choose a function"
    usecase UC1 as "All cities in the world largest population first"
    usecase UC2 as "All cities in a continent largest population first"
    usecase UC3 as "All cities in a region largest population first"
    usecase UC4 as "All cities in a country largest population first"
    usecase UC5 as "All cities in a district largest population first"
    usecase UC6 as "Top N populated cities in the world"
    usecase UC7 as "Top N populated cities in a continent"
    usecase UC8 as "Top N populated cities in a region"
    usecase UC9 as "Top N populated cities in a country"
    usecase UC10 as "Top N populated cities in a district"
    usecase UCa as "Print report"

    CEO - Choice
    Choice ..> UC1
    UC1 .. UC2
    UC2 .. UC3
    UC3 .. UC4
    UC4 .. UC5
    UC5 .. UC6
    UC6 .. UC7
    UC7 .. UC8
    UC8 .. UC9
    UC9 .. UC10
    UC10 ..> UCa : include

    UC1 - Database
    UC2 - Database
    UC3 - Database
    UC4 - Database
    UC5 - Database
    UC6 - Database
    UC7 - Database
    UC8 - Database
    UC9 - Database
    UC10 - Database
}

@enduml