@startuml

actor CEO as "CEO"

rectangle Database

rectangle "Global Reporting System" {

    usecase Choice as "Choose a function"
    usecase UC1 as "Get all countries in the world largest population first"
    usecase UC2 as "Get all countries in the world largest population first"
    usecase UC3 as "Get all countries in the world largest population first"
    usecase UC4 as "Get all countries in the world largest population first"
    usecase UC5 as "Get all countries in the world largest population first"
    usecase UC6 as "Get all countries in the world largest population first"


    usecase UCa as "Print report"

    CEO - Choice
      Choice ..> UC1
      UC1 .. UC2
      UC2 .. UC3
      UC3 .. UC4
      UC4 .. UC5
      UC5 .. UC6

      UC6 ..> UCa : include


      UC1 - Database
          UC2 - Database
          UC3 - Database
          UC4 - Database
          UC5 - Database
          UC6 - Database
}

@enduml